test: tracker comparison

tracker: 
	@echo "Tracking now!"
	@python3 conorsTracker.py
	@echo "Tracking finished."

comparison: 
	@echo "Comparing now!"
	@python3 comparison.py
	@echo "Comparison finished."
